export const HOTEL = {
  nombre: 'Hatuchay Inka Apart Hotel',
  nombreCorto: 'Hatuchay Inka',
  slogan: 'Vive Cajamarca desde el corazón histórico',
  telefono: '+51 977 924 242',
  whatsapp: '+51977924242',
  email: 'reservas@hatuchayinka.com',
  direccion: 'Jr. Dos de Mayo 221, Cajamarca 06000, Perú',
  googleMaps: 'https://maps.google.com/?q=Hatuchay+Inka+Apart+Hotel+Cajamarca',
  googleReviews: 'https://g.page/r/hatuchay-inka-cajamarca/review',
  instagram: 'https://instagram.com/hatuchayinka',
  facebook: 'https://facebook.com/hatuchayinka',
  tripadvisor: 'https://www.tripadvisor.com/Hotel_Review-g319821-d12034375-Reviews-Hatuchay_Inka_Apart_Hotel',
  checkIn: '14:00',
  checkOut: '12:00',
  moneda: 'PEN',
  simboloMoneda: 'S/',
  ruc: '20123456789',
}

export const BANCO = {
  nombre: 'BCP',
  cuentaSoles: '191-12345678-0-12',
  cuentaDolares: '191-98765432-1-23',
  cci: '00219100123456780123',
  titular: 'HATUCHAY INKA APART HOTEL SAC',
  ruc: '20123456789',
}

export const CAJAMARCA_LANDMARKS = [
  {
    id: 1,
    nombre: 'Plaza de Armas',
    descripcion: 'Centro histórico y corazón de Cajamarca',
    imagen: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Plaza_de_Armas_de_Cajamarca.jpg/1280px-Plaza_de_Armas_de_Cajamarca.jpg',
    imagenCircle: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Plaza_de_Armas_de_Cajamarca.jpg/300px-Plaza_de_Armas_de_Cajamarca.jpg',
  },
  {
    id: 2,
    nombre: 'Ventanillas de Otuzco',
    descripcion: 'Cementerio preinca tallado en roca volcánica',
    imagen: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Ventanillas_de_Otuzco.jpg/1280px-Ventanillas_de_Otuzco.jpg',
    imagenCircle: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Ventanillas_de_Otuzco.jpg/300px-Ventanillas_de_Otuzco.jpg',
  },
  {
    id: 3,
    nombre: 'Baños del Inca',
    descripcion: 'Aguas termales del Imperio Incaico',
    imagen: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Ba%C3%B1os_del_Inca_-_Cajamarca.jpg/1280px-Ba%C3%B1os_del_Inca_-_Cajamarca.jpg',
    imagenCircle: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Ba%C3%B1os_del_Inca_-_Cajamarca.jpg/300px-Ba%C3%B1os_del_Inca_-_Cajamarca.jpg',
  },
]

export const HABITACIONES_DATA = [
  {
    id: '102',
    nombre: 'Suite 102 — Deluxe',
    descripcion: 'Amplia suite con vista a la ciudad histórica de Cajamarca. Cuenta con sala de estar, cocina equipada, dormitorio principal y baño privado con agua caliente las 24 horas. Perfecta para parejas o viajeros de negocios que buscan confort y privacidad.',
    tipo: 'suite' as const,
    capacidad: 2,
    precio_por_noche: 220,
    imagenes: [
      '/images/habitaciones/102-1.jpg',
      '/images/habitaciones/102-2.jpg',
      '/images/habitaciones/102-3.jpg',
    ],
    amenidades: ['WiFi gratuito', 'TV cable', 'Cocina equipada', 'Agua caliente 24h', 'Balcón', 'Closet', 'Escritorio', 'Calefacción'],
    disponible: true,
  },
  {
    id: '105',
    nombre: 'Suite 105 — Superior',
    descripcion: 'Lujosa suite de diseño contemporáneo con influencia andina. Dispone de sala-comedor, cocina completa con microondas y refrigeradora, dormitorio doble y baño con tina. Ideal para estadías largas o familias pequeñas.',
    tipo: 'familiar' as const,
    capacidad: 3,
    precio_por_noche: 280,
    imagenes: [
      '/images/habitaciones/105-1.jpg',
      '/images/habitaciones/105-2.jpg',
      '/images/habitaciones/105-3.jpg',
      '/images/habitaciones/105-4.jpg',
    ],
    amenidades: ['WiFi gratuito', 'TV cable Smart', 'Cocina completa', 'Refrigeradora', 'Microondas', 'Tina de baño', 'Agua caliente 24h', 'Calefacción', 'Closet amplio'],
    disponible: true,
  },
  {
    id: '106',
    nombre: 'Apartamento 106 — Familiar',
    descripcion: 'Espacioso apartamento diseñado para familias. Cuenta con dos dormitorios (uno doble y uno twin), sala de estar, comedor y cocina totalmente equipada. El baño incluye ducha de agua caliente permanente y amenidades de cortesía.',
    tipo: 'familiar' as const,
    capacidad: 4,
    precio_por_noche: 350,
    imagenes: [
      '/images/habitaciones/106-1.jpg',
      '/images/habitaciones/106-2.jpg',
      '/images/habitaciones/106-3.jpg',
      '/images/habitaciones/106-4.jpg',
      '/images/habitaciones/106-5.jpg',
      '/images/habitaciones/106-6.jpg',
      '/images/habitaciones/106-7.jpg',
      '/images/habitaciones/106-8.jpg',
    ],
    amenidades: ['WiFi gratuito', 'TV cable 2 habitaciones', 'Cocina equipada', 'Lavandería', 'Agua caliente 24h', 'Calefacción', '2 baños', 'Terraza privada'],
    disponible: true,
  },
  {
    id: '107',
    nombre: 'Suite Presidencial 107',
    descripcion: 'Nuestra suite más exclusiva, ubicada en el piso superior con panorámica al centro histórico de Cajamarca. Decorada con arte andino local, cuenta con sala-comedor de lujo, cocina gourmet, dormitorio principal con cama king y jacuzzi privado.',
    tipo: 'suite' as const,
    capacidad: 2,
    precio_por_noche: 480,
    imagenes: [
      '/images/habitaciones/107-1.jpg',
      '/images/habitaciones/107-2.jpg',
      '/images/habitaciones/107-3.jpg',
      '/images/habitaciones/107-4.jpg',
      '/images/habitaciones/107-5.jpg',
      '/images/habitaciones/107-6.jpg',
      '/images/habitaciones/107-7.jpg',
      '/images/habitaciones/107-8.jpg',
      '/images/habitaciones/107-9.jpg',
      '/images/habitaciones/107-10.jpg',
      '/images/habitaciones/107-11.jpg',
      '/images/habitaciones/107-12.jpg',
      '/images/habitaciones/107-13.jpg',
    ],
    amenidades: ['WiFi Premium', 'Smart TV 55"', 'Cocina gourmet', 'Jacuzzi privado', 'Minibar', 'Vista panorámica', 'Cama King', 'Servicio a la habitación', 'Desayuno incluido'],
    disponible: true,
  },
]
